[package]
name = "susy-jsonrpc-ws-server"
description = "WebSockets server for JSON-RPC"
version = "9.0.0"
authors = ["tomusdrw <tomasz@superstring.ch>"]
license = "MIT"
homepage = "https://github.com/susytech/susy-jsonrpc"
repository = "https://github.com/susytech/susy-jsonrpc"
documentation = "https://susytech.github.io/jsonrpc/json_ws_server/index.html"

[dependencies]
error-chain = { version="0.12", registry="susytech" }
susy-jsonrpc-core = { version = "9.0", registry="susytech" }
susy-jsonrpc-server-utils = { version = "9.0", registry="susytech" }
log = { version="0.4", registry="susytech" }
parking_lot = { version="0.6", registry="susytech" }
slab = { version="0.4", registry="susytech" }
ws = { version="0.7.5", registry="susytech" }

[badges]
travis-ci = { repository = "susytech/susy-jsonrpc", branch = "master"}
