[package]
name = "susy-jsonrpc-tcp-server"
description = "TCP/IP server for JSON-RPC"
version = "8.0.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "MIT"
homepage = "https://github.com/susytech/susy-jsonrpc"
repository = "https://github.com/susytech/susy-jsonrpc"
documentation = "https://susytech.github.io/jsonrpc/susy_jsonrpc_tcp_server/index.html"

[dependencies]
log = "0.3"
parking_lot = "0.4"
tokio-service = "0.1"
susy-jsonrpc-core = { version = "8.0", path = "../core" }
susy-jsonrpc-server-utils = { version = "8.0", path = "../server-utils" }

[dev-dependencies]
lazy_static = "0.2"
env_logger = "0.4"

[badges]
travis-ci = { repository = "susytech/susy-jsonrpc", branch = "master"}
