[package]
description = "Helper macros for susy-jsonrpc-core"
homepage = "https://github.com/susytech/susy-jsonrpc"
repository = "https://github.com/susytech/susy-jsonrpc"
license = "MIT"
name = "susy-jsonrpc-macros"
version = "8.0.0"
authors = ["rphmeier <robert@superstring.ch>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
documentation = "https://susytech.github.io/jsonrpc/susy_jsonrpc_macros/index.html"

[dependencies]
serde = "1.0"
susy-jsonrpc-core = { version = "8.0", path = "../core" }
susy-jsonrpc-pubsub = { version = "8.0", path = "../pubsub" }

[dev-dependencies]
serde_json = "1.0"
susy-jsonrpc-tcp-server = { version = "8.0", path = "../tcp" }

[badges]
travis-ci = { repository = "susytech/susy-jsonrpc", branch = "master"}
